// champions.js

// Comprehensive list of League of Legends Champions
// Includes an 'imageName' property for Data Dragon URL consistency.
// Note: Data Dragon version (e.g., 14.24.1) in the URL might need updating over time.
// This array currently contains 170 champions.
const allLolChampions = [
    // Champion Name: Display Name, imageName: Name used in Data Dragon image URLs
    { id: 1, name: 'Aatrox', imageName: 'Aatrox' },
    { id: 2, name: 'Ahri', imageName: 'Ahri' },
    { id: 3, name: 'Akali', imageName: 'Akali' },
    { id: 4, name: 'Akshan', imageName: 'Akshan' },
    { id: 5, name: 'Alistar', imageName: 'Alistar' },
    { id: 6, name: 'Amumu', imageName: 'Amumu' },
    { id: 7, name: 'Anivia', imageName: 'Anivia' },
    { id: 8, name: 'Annie', imageName: 'Annie' },
    { id: 9, name: 'Aphelios', imageName: 'Aphelios' },
    { id: 10, name: 'Ashe', imageName: 'Ashe' },
    { id: 11, name: 'Aurelion Sol', imageName: 'AurelionSol' }, // No space
    { id: 12, name: 'Azir', imageName: 'Azir' },
    { id: 13, name: 'Bard', imageName: 'Bard' },
    { id: 14, name: 'Bel\'Veth', imageName: 'Belveth' }, // Apostrophe removed
    { id: 15, name: 'Blitzcrank', imageName: 'Blitzcrank' },
    { id: 16, name: 'Brand', imageName: 'Brand' },
    { id: 17, name: 'Braum', imageName: 'Braum' },
    { id: 18, name: 'Briar', imageName: 'Briar' },
    { id: 19, name: 'Caitlyn', imageName: 'Caitlyn' },
    { id: 20, name: 'Camille', imageName: 'Camille' },
    { id: 21, name: 'Cassiopeia', imageName: 'Cassiopeia' },
    { id: 22, name: 'Cho\'Gath', imageName: 'Chogath' }, // Apostrophe removed
    { id: 23, name: 'Corki', imageName: 'Corki' },
    { id: 24, name: 'Darius', imageName: 'Darius' },
    { id: 25, name: 'Diana', imageName: 'Diana' },
    { id: 26, name: 'Dr. Mundo', imageName: 'DrMundo' }, // Dot and space removed
    { id: 27, name: 'Draven', imageName: 'Draven' },
    { id: 28, name: 'Ekko', imageName: 'Ekko' },
    { id: 29, name: 'Elise', imageName: 'Elise' },
    { id: 30, name: 'Evelynn', imageName: 'Evelynn' },
    { id: 31, name: 'Ezreal', imageName: 'Ezreal' },
    { id: 32, name: 'Fiddlesticks', imageName: 'Fiddlesticks' }, // Sometimes 'FiddleSticks', but 'Fiddlesticks' is current
    { id: 33, name: 'Fiora', imageName: 'Fiora' },
    { id: 34, name: 'Fizz', imageName: 'Fizz' },
    { id: 35, name: 'Galio', imageName: 'Galio' },
    { id: 36, name: 'Gangplank', imageName: 'Gangplank' },
    { id: 37, name: 'Garen', imageName: 'Garen' },
    { id: 38, name: 'Gnar', imageName: 'Gnar' },
    { id: 39, name: 'Gragas', imageName: 'Gragas' },
    { id: 40, name: 'Graves', imageName: 'Graves' },
    { id: 41, name: 'Gwen', imageName: 'Gwen' },
    { id: 42, name: 'Hecarim', imageName: 'Hecarim' },
    { id: 43, name: 'Heimerdinger', imageName: 'Heimerdinger' },
    { id: 44, name: 'Hwei', imageName: 'Hwei' },
    { id: 45, name: 'Illaoi', imageName: 'Illaoi' },
    { id: 46, name: 'Irelia', imageName: 'Irelia' },
    { id: 47, name: 'Ivern', imageName: 'Ivern' },
    { id: 48, name: 'Janna', imageName: 'Janna' },
    { id: 49, name: 'Jarvan IV', imageName: 'JarvanIV' }, // Space and Roman numeral removed
    { id: 50, name: 'Jax', imageName: 'Jax' },
    { id: 51, name: 'Jayce', imageName: 'Jayce' },
    { id: 52, name: 'Jhin', imageName: 'Jhin' },
    { id: 53, name: 'Jinx', imageName: 'Jinx' },
    { id: 54, name: 'K\'Sante', imageName: 'KSante' }, // Apostrophe removed
    { id: 55, name: 'Kai\'Sa', imageName: 'Kaisa' }, // Apostrophe removed
    { id: 56, name: 'Kalista', imageName: 'Kalista' },
    { id: 57, name: 'Karma', imageName: 'Karma' },
    { id: 58, name: 'Karthus', imageName: 'Karthus' },
    { id: 59, name: 'Kassadin', imageName: 'Kassadin' },
    { id: 60, name: 'Katarina', imageName: 'Katarina' },
    { id: 61, name: 'Kayle', imageName: 'Kayle' },
    { id: 62, name: 'Kayn', imageName: 'Kayn' },
    { id: 63, name: 'Kennen', imageName: 'Kennen' },
    { id: 64, name: 'Kha\'Zix', imageName: 'Khazix' }, // Apostrophe removed
    { id: 65, name: 'Kindred', imageName: 'Kindred' },
    { id: 66, name: 'Kled', imageName: 'Kled' },
    { id: 67, name: 'Kog\'Maw', imageName: 'KogMaw' }, // Apostrophe removed, no space
    { id: 68, name: 'LeBlanc', imageName: 'Leblanc' }, // Capitalization
    { id: 69, name: 'Lee Sin', imageName: 'LeeSin' }, // No space
    { id: 70, name: 'Leona', imageName: 'Leona' },
    { id: 71, name: 'Lillia', imageName: 'Lillia' },
    { id: 72, name: 'Lissandra', imageName: 'Lissandra' },
    { id: 73, name: 'Lucian', imageName: 'Lucian' },
    { id: 74, name: 'Lulu', imageName: 'Lulu' },
    { id: 75, name: 'Lux', imageName: 'Lux' },
    { id: 76, name: 'Malphite', imageName: 'Malphite' },
    { id: 77, name: 'Malzahar', imageName: 'Malzahar' },
    { id: 78, name: 'Maokai', imageName: 'Maokai' },
    { id: 79, name: 'Master Yi', imageName: 'MasterYi' }, // No space
    { id: 80, name: 'Milio', imageName: 'Milio' },
    { id: 81, name: 'Miss Fortune', imageName: 'MissFortune' }, // No space
    { id: 82, name: 'Mordekaiser', imageName: 'Mordekaiser' },
    { id: 83, name: 'Morgana', imageName: 'Morgana' },
    { id: 84, name: 'Naafiri', imageName: 'Naafiri' },
    { id: 85, name: 'Nami', imageName: 'Nami' },
    { id: 86, name: 'Nasus', imageName: 'Nasus' },
    { id: 87, name: 'Nautilus', imageName: 'Nautilus' },
    { id: 88, name: 'Neeko', imageName: 'Neeko' },
    { id: 89, name: 'Nidalee', imageName: 'Nidalee' },
    { id: 90, name: 'Nilah', imageName: 'Nilah' },
    { id: 91, name: 'Nocturne', imageName: 'Nocturne' },
    { id: 92, name: 'Nunu & Willump', imageName: 'Nunu' }, // Uses Nunu
    { id: 93, name: 'Olaf', imageName: 'Olaf' },
    { id: 94, name: 'Orianna', imageName: 'Orianna' },
    { id: 95, name: 'Ornn', imageName: 'Ornn' },
    { id: 96, name: 'Pantheon', imageName: 'Pantheon' },
    { id: 97, name: 'Poppy', imageName: 'Poppy' },
    { id: 98, name: 'Pyke', imageName: 'Pyke' },
    { id: 99, name: 'Qiyana', imageName: 'Qiyana' },
    { id: 100, name: 'Quinn', imageName: 'Quinn' },
    { id: 101, name: 'Rakan', imageName: 'Rakan' },
    { id: 102, name: 'Rammus', imageName: 'Rammus' },
    { id: 103, name: 'Rek\'Sai', imageName: 'RekSai' }, // Apostrophe removed
    { id: 104, name: 'Rell', imageName: 'Rell' },
    { id: 105, name: 'Renata Glasc', imageName: 'Renata' }, // Uses Renata
    { id: 106, name: 'Renekton', imageName: 'Renekton' },
    { id: 107, name: 'Rengar', imageName: 'Rengar' },
    { id: 108, name: 'Riven', imageName: 'Riven' },
    { id: 109, name: 'Rumble', imageName: 'Rumble' },
    { id: 110, name: 'Ryze', imageName: 'Ryze' },
    { id: 111, name: 'Samira', imageName: 'Samira' },
    { id: 112, name: 'Sejuani', imageName: 'Sejuani' },
    { id: 113, name: 'Senna', imageName: 'Senna' },
    { id: 114, name: 'Seraphine', imageName: 'Seraphine' },
    { id: 115, name: 'Sett', imageName: 'Sett' },
    { id: 116, name: 'Shaco', imageName: 'Shaco' },
    { id: 117, name: 'Shen', imageName: 'Shen' },
    { id: 118, name: 'Shyvana', imageName: 'Shyvana' },
    { id: 119, name: 'Singed', imageName: 'Singed' },
    { id: 120, name: 'Sion', imageName: 'Sion' },
    { id: 121, name: 'Sivir', imageName: 'Sivir' },
    { id: 122, name: 'Skarner', imageName: 'Skarner' },
    { id: 123, name: 'Smolder', imageName: 'Smolder' },
    { id: 124, name: 'Sona', imageName: 'Sona' },
    { id: 125, name: 'Soraka', imageName: 'Soraka' },
    { id: 126, name: 'Swain', imageName: 'Swain' },
    { id: 127, name: 'Sylas', imageName: 'Sylas' },
    { id: 128, name: 'Syndra', imageName: 'Syndra' },
    { id: 129, name: 'Tahm Kench', imageName: 'TahmKench' }, // No space
    { id: 130, name: 'Taliyah', imageName: 'Taliyah' },
    { id: 131, name: 'Talon', imageName: 'Talon' },
    { id: 132, name: 'Taric', imageName: 'Taric' },
    { id: 133, name: 'Teemo', imageName: 'Teemo' },
    { id: 134, name: 'Thresh', imageName: 'Thresh' },
    { id: 135, name: 'Tristana', imageName: 'Tristana' },
    { id: 136, name: 'Trundle', imageName: 'Trundle' },
    { id: 137, name: 'Tryndamere', imageName: 'Tryndamere' },
    { id: 138, name: 'Twisted Fate', imageName: 'TwistedFate' }, // No space
    { id: 139, name: 'Twitch', imageName: 'Twitch' },
    { id: 140, name: 'Udyr', imageName: 'Udyr' },
    { id: 141, name: 'Urgot', imageName: 'Urgot' },
    { id: 142, name: 'Varus', imageName: 'Varus' },
    { id: 143, name: 'Vayne', imageName: 'Vayne' },
    { id: 144, name: 'Veigar', imageName: 'Veigar' },
    { id: 145, name: 'Vel\'Koz', imageName: 'Velkoz' }, // Apostrophe removed
    { id: 146, name: 'Vex', imageName: 'Vex' },
    { id: 147, name: 'Vi', imageName: 'Vi' },
    { id: 148, name: 'Viego', imageName: 'Viego' },
    { id: 149, name: 'Viktor', imageName: 'Viktor' },
    { id: 150, name: 'Vladimir', imageName: 'Vladimir' },
    { id: 151, name: 'Volibear', imageName: 'Volibear' },
    { id: 152, name: 'Warwick', imageName: 'Warwick' },
    { id: 153, name: 'Wukong', imageName: 'MonkeyKing' }, // Special case
    { id: 154, name: 'Xayah', imageName: 'Xayah' },
    { id: 155, name: 'Xerath', imageName: 'Xerath' },
    { id: 156, name: 'Xin Zhao', imageName: 'XinZhao' }, // No space
    { id: 157, name: 'Yasuo', imageName: 'Yasuo' },
    { id: 158, name: 'Yone', imageName: 'Yone' },
    { id: 159, name: 'Yorick', imageName: 'Yorick' },
    { id: 160, name: 'Yuumi', imageName: 'Yuumi' },
    { id: 161, name: 'Zac', imageName: 'Zac' },
    { id: 162, name: 'Zed', imageName: 'Zed' },
    { id: 163, name: 'Zeri', imageName: 'Zeri' },
    { id: 164, name: 'Ziggs', imageName: 'Ziggs' },
    { id: 165, name: 'Zilean', imageName: 'Zilean' },
    { id: 166, name: 'Zoe', imageName: 'Zoe' },
    { id: 167, name: 'Zyra', imageName: 'Zyra' },
    // Added champions
    { id: 168, name: 'Aurora', imageName: 'Aurora' },
    { id: 169, name: 'Ambessa', imageName: 'Ambessa' },
    { id: 170, name: 'Mel', imageName: 'Mel' }
  ];
  
  // Your Team's Tier List / Champion Pool
  // Structure: { PlayerNameOrRole: { ChampionName: Tier, ... }, ... }
  // Example - Replace with your actual team data!
  const teamTierList = {
    "Top": {
      "Ambessa": "S",
      "Jayce": "S",
      "Gwen": "S",
      "Rumble": "S",
      "K'Sante": "S",
      "Volibear": "A",
      "Gnar": "A",
      "Yone": "A",
      "Gragas": "A",
      "Jax": "A",
      "Kennen": "A",
      "Camille": "A",
      "Aatrox": "A",
      "Aurora": "A",
      "Sion": "A",
      "Gangplank": "B",
      "Renekton": "B",
      "Illaoi": "B"
    },
    "Jungle": {
      "Lillia": "S",
      "Vi": "S",
      "Ivern": "S",
      "Zyra": "S",
      "Amumu": "S",
      "Naafiri": "S",
      "Wukong": "S",
      "Pantheon": "S",
      "Viego": "S",
      "Skarner": "S",
      "Nocturne": "S",
      "Maokai": "S",
      "Karthus": "S",
      "Xin Zhao": "S",
      "Jarvan IV": "S",
      "Gwen": "A",
      "Volibear": "A",
      "Sejuani": "B"
    },
    "Mid": {
      "Gwen": "S",
      "Yone": "S",
      "Naafiri": "S",
      "Ahri": "S",
      "Mel": "S",
      "Aurora": "S",
      "Galio": "S",
      "Viktor": "S",
      "Xerath": "S",
      "Orianna": "S",
      "Cassiopeia": "S",
      "Corki": "S",
      "Swain": "S",
      "Hwei": "S",
      "Sylas": "S",
      "Syndra": "S",
      "Vex": "A",
      "Ryze": "A",
      "Lux": "A",
      "Tristana": "A",
      "Pantheon": "A",
      "Azir": "A",
      "Tryndamere": "A",
      "Taliyah": "A",
      "Lissandra": "A",
      "Lucian": "A",
      "Mordekaiser": "A",
      "Smolder": "B",
      "Akali": "B",
      "Leblanc": "B"
    },
    "Adc": {
      "Twitch": "S",
      "Ezreal": "S",
      "Kog'Maw": "S",
      "Varus": "S",
      "Xayah": "S",
      "Draven": "S",
      "Kalista": "S",
      "Kai'Sa": "S",
      "Jinx": "S",
      "Ashe": "S",
      "Sivir": "A",
      "Lucian": "A",
      "Zeri": "A",
      "Vayne": "A",
      "Samira": "A",
      "Karthus": "A",
      "Tristana": "B",
      "Corki": "B",
      "Aphelios": "B",
      "Yasuo": "B"
    },
    "Supp": {
      "Alistar": "S",
      "Rell": "S",
      "Seraphine": "S",
      "Rakan": "S",
      "Maokai": "S",
      "Nautilus": "S",
      "Lulu": "S",
      "Leona": "S",
      "Janna": "S",
      "Bard": "S",
      "Braum": "S",
      "Ashe": "S",
      "Milio": "S",
      "Hwei": "A",
      "Nami": "A",
      "Pyke": "A",
      "Lux": "A",
      "Blitzcrank": "A",
      "Poppy": "A",
      "Thresh": "A",
      "Lissandra": "A",
      "Twisted Fate": "A",
      "Caitlyn": "A",
      "Sejuani": "A",
      "Galio": "A",
      "Jax": "B",
      "K'Sante": "B",
      "Camille": "B",
      "Shen": "B",
      "Pantheon": "B",
      "Zilean": "B"
    }
  };
  
  // Make the data available globally
  window.allLolChampions = allLolChampions;
  window.teamTierList = teamTierList;
  
  console.log("Champion data loaded:", window.allLolChampions.length, "total champions in the list.");
  console.log("Team tier list loaded for roles:", Object.keys(window.teamTierList));
  
  